#!/bin/bash
sum=0
sides=6
count=2
while [[$count -gt 0]]; do #loop
  case $1 in
    -h | --help)
      echo "Please type "
      exit 0
      ;;
  esac
  case $1 in
    -c | --count) shift
      if [[$1 -lt 1 || $1 -gt 9]]; then
        echo "Please enter a number of dice to roll between 1-9"
        exit
      fi
      count=$1
      ;;
